question_data = [
                {"category": "Entertainment",
                "type": "boolean",
                "difficulty": "easy",
                "question": "The movie The Nightmare before Christmas was all done with physical objects.",
                "correct_answer": "True",
                "incorrect_answers": ["False"]},

                {"category": "Entertainment",
                "type": "boolean",
                "difficulty": "easy",
                "question": "The 2010 film The Social Network is a biographical drama film about MySpace founder Tom Anderson.",
                "correct_answer": "False",
                "incorrect_answers": ["True"]},

                {"category": "Entertainment",
                "type": "boolean",
                "difficulty": "easy",
                "question": "The word Inception came from the 2010 blockbuster hit Inception.",
                "correct_answer": "False",
                "incorrect_answers": ["True"]},

                {"category": "Entertainment",
                "type": "boolean",
                "difficulty": "easy",
                "question": "In the original script of &quot;The Matrix&quot;, the machines used humans as additional computing power instead of batteries.",
                "correct_answer": "True",
                "incorrect_answers": ["False"]},

                {"category": "Entertainment",
                "type": "boolean",
                "difficulty": "easy",
                "question": "Samuel L. Jackson had the words,Bad Bro in-scripted on his lightsaber during the filming of Star Wars.",
                "correct_answer": "True",
                "incorrect_answers": ["False"]},

                {"category": "Entertainment",
                "type": "boolean",
                "difficulty": "easy",
                "question": "In Alfred Hitchcock film Psycho it is said he used chocolate syrup to simulate the blood in the famous shower scene from ",
                "correct_answer": "True",
                "incorrect_answers": ["False"]},

                {"category": "Entertainment",
                "type": "boolean",
                "difficulty": "easy",
                "question": "In the original Star Wars trilogy, Alec Guinness provided the voice for Darth Vader.",
                "correct_answer": "False",
                "incorrect_answers": ["True"]},

                {"category": "Entertainment",
                "type": "boolean",
                "difficulty": "easy",
                "question": "Brandon Routh plays the titular character in the movie John Wick.",
                "correct_answer": "False",
                "incorrect_answers": ["True"]},

                {"category": "Entertainment",
                "type": "boolean",
                "difficulty": "easy",
                "question": "Actor Tommy Chong served prison time.",
                "correct_answer": "True",
                "incorrect_answers": ["False"]},

                {"category": "Entertainment",
                "type": "boolean",
                "difficulty": "easy",
                "question": "Foodfight! earned less than $80,000 at box office.",
                "correct_answer": "True",
                "incorrect_answers": ["False"]}
                ]
